[2025-05-04T18:39:55.556+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-04T18:39:55.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_iceberg_example.create_iceberg_tables manual__2025-05-04T18:37:53.365354+00:00 [queued]>
[2025-05-04T18:39:55.575+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_iceberg_example.create_iceberg_tables manual__2025-05-04T18:37:53.365354+00:00 [queued]>
[2025-05-04T18:39:55.576+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-04T18:39:55.583+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): create_iceberg_tables> on 2025-05-04 18:37:53.365354+00:00
[2025-05-04T18:39:55.588+0000] {standard_task_runner.py:63} INFO - Started process 613 to run task
[2025-05-04T18:39:55.590+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_iceberg_example', 'create_iceberg_tables', 'manual__2025-05-04T18:37:53.365354+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/dbt_iceberg_dag.py', '--cfg-path', '/tmp/tmp8hpuczfn']
[2025-05-04T18:39:55.591+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask create_iceberg_tables
[2025-05-04T18:39:55.619+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_iceberg_example.create_iceberg_tables manual__2025-05-04T18:37:53.365354+00:00 [running]> on host 27fc0593f179
[2025-05-04T18:39:55.668+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_iceberg_example' AIRFLOW_CTX_TASK_ID='create_iceberg_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T18:37:53.365354+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-04T18:37:53.365354+00:00'
[2025-05-04T18:39:55.668+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-04T18:39:55.677+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-04T18:39:55.678+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    trino --server http://trino:8080 --catalog iceberg --schema default --execute "\n    CREATE SCHEMA IF NOT EXISTS iceberg.raw;\n\n    CREATE TABLE IF NOT EXISTS iceberg.raw.products (\n        id INTEGER,\n        name VARCHAR,\n        category VARCHAR,\n        price DOUBLE,\n        date DATE\n    )\n    WITH (\n        format = \'PARQUET\',\n        location = \'s3a://iceberg-data/raw/products/\'\n    );\n\n    CREATE TABLE IF NOT EXISTS iceberg.raw.sales (\n        sale_id INTEGER,\n        product_id INTEGER,\n        quantity INTEGER,\n        total DOUBLE,\n        date DATE\n    )\n    WITH (\n        format = \'PARQUET\',\n        location = \'s3a://iceberg-data/raw/sales/\'\n    );\n    "\n    ']
[2025-05-04T18:39:55.686+0000] {subprocess.py:86} INFO - Output:
[2025-05-04T18:39:55.688+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 2: trino: command not found
[2025-05-04T18:39:55.688+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-05-04T18:39:55.688+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-04T18:39:55.695+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-05-04T18:39:55.697+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_iceberg_example, task_id=create_iceberg_tables, run_id=manual__2025-05-04T18:37:53.365354+00:00, execution_date=20250504T183753, start_date=20250504T183955, end_date=20250504T183955
[2025-05-04T18:39:55.705+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 60 for task create_iceberg_tables (Bash command failed. The command returned a non-zero exit code 127.; 613)
[2025-05-04T18:39:55.722+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-04T18:39:55.722+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
