[2025-05-04T19:29:47.638+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-04T19:29:47.651+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_iceberg_example.insert_data_into_trino manual__2025-05-04T19:29:44.377206+00:00 [queued]>
[2025-05-04T19:29:47.655+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_iceberg_example.insert_data_into_trino manual__2025-05-04T19:29:44.377206+00:00 [queued]>
[2025-05-04T19:29:47.656+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-04T19:29:47.662+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_data_into_trino> on 2025-05-04 19:29:44.377206+00:00
[2025-05-04T19:29:47.667+0000] {standard_task_runner.py:63} INFO - Started process 1356 to run task
[2025-05-04T19:29:47.669+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_iceberg_example', 'insert_data_into_trino', 'manual__2025-05-04T19:29:44.377206+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/dbt_iceberg_dag.py', '--cfg-path', '/tmp/tmpajkpw70h']
[2025-05-04T19:29:47.669+0000] {standard_task_runner.py:91} INFO - Job 86: Subtask insert_data_into_trino
[2025-05-04T19:29:47.694+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_iceberg_example.insert_data_into_trino manual__2025-05-04T19:29:44.377206+00:00 [running]> on host 27fc0593f179
[2025-05-04T19:29:47.740+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_iceberg_example' AIRFLOW_CTX_TASK_ID='insert_data_into_trino' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T19:29:44.377206+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-04T19:29:44.377206+00:00'
[2025-05-04T19:29:47.741+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-04T19:29:47.927+0000] {dbapi.py:285} WARNING - EXECUTE IMMEDIATE not available for trino:8080; defaulting to legacy prepared statements (TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 1:19: mismatched input ''SELECT 1''. Expecting: 'USING', <EOF>", query_id=20250504_192612_00204_scynm))
[2025-05-04T19:29:50.825+0000] {logging_mixin.py:188} INFO - Dados inseridos com sucesso nas tabelas Iceberg
[2025-05-04T19:29:50.827+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-04T19:29:50.827+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-04T19:29:50.836+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_iceberg_example, task_id=insert_data_into_trino, run_id=manual__2025-05-04T19:29:44.377206+00:00, execution_date=20250504T192944, start_date=20250504T192947, end_date=20250504T192950
[2025-05-04T19:29:50.887+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-04T19:29:50.888+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
