[2025-05-04T18:32:05.969+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-04T18:32:05.986+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_iceberg_example.create_iceberg_tables manual__2025-05-04T18:30:03.059347+00:00 [queued]>
[2025-05-04T18:32:05.992+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_iceberg_example.create_iceberg_tables manual__2025-05-04T18:30:03.059347+00:00 [queued]>
[2025-05-04T18:32:05.993+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-04T18:32:06.002+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): create_iceberg_tables> on 2025-05-04 18:30:03.059347+00:00
[2025-05-04T18:32:06.006+0000] {standard_task_runner.py:63} INFO - Started process 495 to run task
[2025-05-04T18:32:06.008+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_iceberg_example', 'create_iceberg_tables', 'manual__2025-05-04T18:30:03.059347+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dbt_iceberg_dag.py', '--cfg-path', '/tmp/tmpko4folym']
[2025-05-04T18:32:06.009+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask create_iceberg_tables
[2025-05-04T18:32:06.040+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_iceberg_example.create_iceberg_tables manual__2025-05-04T18:30:03.059347+00:00 [running]> on host 27fc0593f179
[2025-05-04T18:32:06.085+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_iceberg_example' AIRFLOW_CTX_TASK_ID='create_iceberg_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T18:30:03.059347+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-04T18:30:03.059347+00:00'
[2025-05-04T18:32:06.086+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-04T18:32:06.093+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-04T18:32:06.094+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    /usr/local/bin/trino --server http://trino:8080 --catalog iceberg --schema default --execute "\n    CREATE SCHEMA IF NOT EXISTS iceberg.raw;\n\n    CREATE TABLE IF NOT EXISTS iceberg.raw.products (\n        id INTEGER,\n        name VARCHAR,\n        category VARCHAR,\n        price DOUBLE,\n        date DATE\n    )\n    WITH (\n        format = \'PARQUET\',\n        location = \'s3a://iceberg-data/raw/products/\'\n    );\n\n    CREATE TABLE IF NOT EXISTS iceberg.raw.sales (\n        sale_id INTEGER,\n        product_id INTEGER,\n        quantity INTEGER,\n        total DOUBLE,\n        date DATE\n    )\n    WITH (\n        format = \'PARQUET\',\n        location = \'s3a://iceberg-data/raw/sales/\'\n    );\n    "\n    ']
[2025-05-04T18:32:06.103+0000] {subprocess.py:86} INFO - Output:
[2025-05-04T18:32:06.104+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 2: /usr/local/bin/trino: No such file or directory
[2025-05-04T18:32:06.105+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-05-04T18:32:06.105+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-04T18:32:06.112+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-05-04T18:32:06.114+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_iceberg_example, task_id=create_iceberg_tables, run_id=manual__2025-05-04T18:30:03.059347+00:00, execution_date=20250504T183003, start_date=20250504T183205, end_date=20250504T183206
[2025-05-04T18:32:06.122+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 54 for task create_iceberg_tables (Bash command failed. The command returned a non-zero exit code 127.; 495)
[2025-05-04T18:32:06.140+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-04T18:32:06.141+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
