[2025-05-05T09:50:34.688+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-05T09:50:34.700+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_iceberg_example.dbt_debug manual__2025-05-05T09:50:23.548536+00:00 [queued]>
[2025-05-05T09:50:34.704+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_iceberg_example.dbt_debug manual__2025-05-05T09:50:23.548536+00:00 [queued]>
[2025-05-05T09:50:34.706+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-05-05T09:50:34.713+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_debug> on 2025-05-05 09:50:23.548536+00:00
[2025-05-05T09:50:34.717+0000] {standard_task_runner.py:63} INFO - Started process 103 to run task
[2025-05-05T09:50:34.718+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_iceberg_example', 'dbt_debug', 'manual__2025-05-05T09:50:23.548536+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dbt_iceberg_dag.py', '--cfg-path', '/tmp/tmpje25_qqm']
[2025-05-05T09:50:34.720+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask dbt_debug
[2025-05-05T09:50:34.751+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_iceberg_example.dbt_debug manual__2025-05-05T09:50:23.548536+00:00 [running]> on host 92b88004addd
[2025-05-05T09:50:34.805+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_iceberg_example' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T09:50:23.548536+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T09:50:23.548536+00:00'
[2025-05-05T09:50:34.805+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-05T09:50:34.814+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T09:50:34.815+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt debug --profiles-dir .']
[2025-05-05T09:50:34.824+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T09:50:36.651+0000] {subprocess.py:93} INFO - [0m09:50:36  Running with dbt=1.7.0
[2025-05-05T09:50:36.653+0000] {subprocess.py:93} INFO - [0m09:50:36  dbt version: 1.7.0
[2025-05-05T09:50:36.653+0000] {subprocess.py:93} INFO - [0m09:50:36  python version: 3.11.9
[2025-05-05T09:50:36.654+0000] {subprocess.py:93} INFO - [0m09:50:36  python path: /home/***/.local/bin/python
[2025-05-05T09:50:36.655+0000] {subprocess.py:93} INFO - [0m09:50:36  os info: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-05-05T09:50:36.732+0000] {subprocess.py:93} INFO - [0m09:50:36  Using profiles dir at .
[2025-05-05T09:50:36.733+0000] {subprocess.py:93} INFO - [0m09:50:36  Using profiles.yml file at ./profiles.yml
[2025-05-05T09:50:36.733+0000] {subprocess.py:93} INFO - [0m09:50:36  Using dbt_project.yml file at /opt/***/dbt_project/dbt_project.yml
[2025-05-05T09:50:36.734+0000] {subprocess.py:93} INFO - [0m09:50:36  adapter type: trino
[2025-05-05T09:50:36.735+0000] {subprocess.py:93} INFO - [0m09:50:36  adapter version: 1.7.0
[2025-05-05T09:50:36.784+0000] {subprocess.py:93} INFO - [0m09:50:36  Configuration:
[2025-05-05T09:50:36.785+0000] {subprocess.py:93} INFO - [0m09:50:36    profiles.yml file [[32mOK found and valid[0m]
[2025-05-05T09:50:36.785+0000] {subprocess.py:93} INFO - [0m09:50:36    dbt_project.yml file [[32mOK found and valid[0m]
[2025-05-05T09:50:36.786+0000] {subprocess.py:93} INFO - [0m09:50:36  Required dependencies:
[2025-05-05T09:50:36.791+0000] {subprocess.py:93} INFO - [0m09:50:36   - git [[32mOK found[0m]
[2025-05-05T09:50:36.791+0000] {subprocess.py:93} INFO - 
[2025-05-05T09:50:36.791+0000] {subprocess.py:93} INFO - [0m09:50:36  Connection:
[2025-05-05T09:50:36.792+0000] {subprocess.py:93} INFO - [0m09:50:36    host: trino
[2025-05-05T09:50:36.793+0000] {subprocess.py:93} INFO - [0m09:50:36    port: 8080
[2025-05-05T09:50:36.793+0000] {subprocess.py:93} INFO - [0m09:50:36    user: ***
[2025-05-05T09:50:36.794+0000] {subprocess.py:93} INFO - [0m09:50:36    database: iceberg
[2025-05-05T09:50:36.795+0000] {subprocess.py:93} INFO - [0m09:50:36    schema: default
[2025-05-05T09:50:36.796+0000] {subprocess.py:93} INFO - [0m09:50:36    cert: None
[2025-05-05T09:50:36.796+0000] {subprocess.py:93} INFO - [0m09:50:36    prepared_statements_enabled: True
[2025-05-05T09:50:36.797+0000] {subprocess.py:93} INFO - [0m09:50:36  Registered adapter: trino=1.7.0
[2025-05-05T09:50:36.846+0000] {subprocess.py:93} INFO - [0m09:50:36    Connection test: [[32mOK connection ok[0m]
[2025-05-05T09:50:36.846+0000] {subprocess.py:93} INFO - 
[2025-05-05T09:50:36.846+0000] {subprocess.py:93} INFO - [0m09:50:36  [32mAll checks passed![0m
[2025-05-05T09:50:37.907+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-05T09:50:37.908+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-05T09:50:37.922+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_iceberg_example, task_id=dbt_debug, run_id=manual__2025-05-05T09:50:23.548536+00:00, execution_date=20250505T095023, start_date=20250505T095034, end_date=20250505T095037
[2025-05-05T09:50:37.936+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-05T09:50:37.936+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
