[2025-05-04T19:20:14.057+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-04T19:20:14.069+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_iceberg_example.insert_data_into_trino manual__2025-05-04T19:18:11.309260+00:00 [queued]>
[2025-05-04T19:20:14.074+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_iceberg_example.insert_data_into_trino manual__2025-05-04T19:18:11.309260+00:00 [queued]>
[2025-05-04T19:20:14.074+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-04T19:20:14.081+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_data_into_trino> on 2025-05-04 19:18:11.309260+00:00
[2025-05-04T19:20:14.086+0000] {standard_task_runner.py:63} INFO - Started process 1215 to run task
[2025-05-04T19:20:14.088+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_iceberg_example', 'insert_data_into_trino', 'manual__2025-05-04T19:18:11.309260+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/dbt_iceberg_dag.py', '--cfg-path', '/tmp/tmp_4p00cjt']
[2025-05-04T19:20:14.088+0000] {standard_task_runner.py:91} INFO - Job 75: Subtask insert_data_into_trino
[2025-05-04T19:20:14.114+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_iceberg_example.insert_data_into_trino manual__2025-05-04T19:18:11.309260+00:00 [running]> on host 27fc0593f179
[2025-05-04T19:20:14.161+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_iceberg_example' AIRFLOW_CTX_TASK_ID='insert_data_into_trino' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T19:18:11.309260+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-04T19:18:11.309260+00:00'
[2025-05-04T19:20:14.162+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-04T19:20:14.180+0000] {transaction.py:82} INFO - transaction started: a37f6c73-04dd-41bd-a193-996b927bc515
[2025-05-04T19:20:14.200+0000] {logging_mixin.py:188} INFO - Erro ao inserir dados: TrinoUserError(type=USER_ERROR, name=AUTOCOMMIT_WRITE_CONFLICT, message="Catalog only supports writes using autocommit: iceberg", query_id=20250504_191703_00168_scynm)
[2025-05-04T19:20:14.202+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-04T19:20:14.203+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dbt_iceberg_dag.py", line 159, in insert_data_into_trino
    cursor.execute("DELETE FROM iceberg.raw.products")
  File "/home/airflow/.local/lib/python3.10/site-packages/trino/dbapi.py", line 592, in execute
    self._iterator = iter(self._query.execute())
  File "/home/airflow/.local/lib/python3.10/site-packages/trino/client.py", line 810, in execute
    self._result.rows += self.fetch()
  File "/home/airflow/.local/lib/python3.10/site-packages/trino/client.py", line 830, in fetch
    status = self._request.process(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/trino/client.py", line 609, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=AUTOCOMMIT_WRITE_CONFLICT, message="Catalog only supports writes using autocommit: iceberg", query_id=20250504_191703_00168_scynm)
[2025-05-04T19:20:14.211+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_iceberg_example, task_id=insert_data_into_trino, run_id=manual__2025-05-04T19:18:11.309260+00:00, execution_date=20250504T191811, start_date=20250504T192014, end_date=20250504T192014
[2025-05-04T19:20:14.218+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 75 for task insert_data_into_trino (TrinoUserError(type=USER_ERROR, name=AUTOCOMMIT_WRITE_CONFLICT, message="Catalog only supports writes using autocommit: iceberg", query_id=20250504_191703_00168_scynm); 1215)
[2025-05-04T19:20:14.259+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-04T19:20:14.260+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
